apiVersion: v1
kind: Service
metadata:
  name: mon-app-service
  labels:
    app: mon-app
spec:
  selector:
    app: mon-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
